import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import { AuthContextProvider } from "./_utils/auth-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CPRG 306 Web Development 2 Assignments",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}><AuthContextProvider>{children}</AuthContextProvider></body>
    </html>
  );
}
